import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-photos-page',
  templateUrl: './photos-page.component.html',
  styleUrls: ['./photos-page.component.scss']
})
export class PhotosPageComponent implements OnInit {
  base_lq: string = "/assets/engagement_photos_lq/";
  base_hd: string = "/assets/engagement_photos_hd/";

  photosLQ = [
    {path: `${this.base_lq}MASON-1.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-2.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-3.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-4.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-5.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-6.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-7.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-8.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-9.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-10.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-11.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-12.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-13.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-14.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-15.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-16.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-17.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-18.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-19.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-20.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-21.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-22.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-23.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-24.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-25.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-26.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-27.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-28.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-29.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-30.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-31.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-32.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-33.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-34.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-35.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-36.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-37.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-38.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-39.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-40.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-41.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-42.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-43.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-44.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-45.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-46.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-47.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-48.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-49.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-50.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-51.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-52.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-53.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-54.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-55.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-56.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-57.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-58.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-59.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-60.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-61.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-62.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-63.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-64.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-65.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-66.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-67.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-68.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-69.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-70.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-71.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-72.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-73.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-74.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-75.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-76.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-77.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-78.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-79.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-80.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-81.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-83.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-82.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-84.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-85.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-86.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-87.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-88.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-89.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-90.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-91.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-92.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-93.jpg`, alt: 'Garrett and Claire kissing, ew'}
  ];

  photosHD = [
    {path: `${this.base_hd}MASON-1.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-2.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-3.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-4.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_hd}MASON-5.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_hd}MASON-6.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-7.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-8.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-9.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-10.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-11.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-12.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-13.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-14.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-15.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-16.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-17.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_hd}MASON-18.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-19.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_hd}MASON-20.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-21.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-22.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_hd}MASON-23.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_hd}MASON-24.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-25.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-26.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-27.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-28.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-29.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_hd}MASON-30.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-31.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-32.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-33.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-34.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-35.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-36.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-37.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-38.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-39.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-40.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-41.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-42.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-43.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-44.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-45.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-46.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-47.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-48.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-49.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-50.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-51.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-52.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-53.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-54.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-55.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-56.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-57.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-58.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-59.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-60.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-61.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-62.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-63.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-64.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-65.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-66.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-67.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-68.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-69.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-70.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-71.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-72.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-73.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-74.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-75.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-76.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-77.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-78.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-79.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-80.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-81.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-83.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-82.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-84.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-85.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-86.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-87.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-88.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-89.jpg`, alt: 'Garrett and Claire kissing, ew'},
    {path: `${this.base_lq}MASON-90.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-91.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-92.jpg`, alt: 'Garrett and Claire kissing, ew'},
    // {path: `${this.base_lq}MASON-93.jpg`, alt: 'Garrett and Claire kissing, ew'}
  ];

  constructor() { }

  ngOnInit(): void {
  }

}
